
version: '3'
services:
  webpilot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
